name: lint and test server on push
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: timbru31/node-alpine-git
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: run lint and test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
      - run: yarn lint
